server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.43.238.143:8036/yanxi?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&initialTimeout=10
    username: yanxi
    password: yanxi123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # Connection pool settings
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      # Connection validation
      connection-test-query: SELECT 1
      validation-timeout: 3000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yanxi.yanxiapi.entity

logging:
  level:
    org.springframework.security: DEBUG
    com.yanxi.yanxiapi: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool.HikariPool: DEBUG

file:
  upload-dir: ./uploads/homework 