server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.43.238.143:8036/yanxi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yanxi.yanxiapi.entity

logging:
  level:
    org.springframework.security: DEBUG
    com.yanxi.yanxiapi: DEBUG

file:
  upload-dir: ./uploads/homework 